insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(1,'AGUA SANITARIA','Q2',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(2,'ODORIZANTE DE AMBIENTE','Q2',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(3,'INCETICIDA','Q2',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(4,'ALCOOL 92,8','Q2',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(5,'LIMPADOR PARA USO GERAL','Q2',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(6,'DETERGENTE','Q2',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(7,'ESPONJA DE LIMPEZA','Q2',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(8,'PEDRA SANITARIA','Q2',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(9,'PASTA MULTI-USO','Q2',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(10,'PANO MULTI-USO','Q2',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(11,'VASSOURA','Q2',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(12,'SACO LIXO 40L PCT. COM 100','Q2',0,0,5);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(13,'TOALHA DE PAPEL SANITARIO','Q2',0,0,7);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(14,'PAPEL HIGIENICO 4 ROLOS','Q2',0,0,13);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(15,'PANO DE CHAO','Q2',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(16,'TELEFONE','Q4',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(17,'LUVA PVC EMBORRACHADA','Q3',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(18,'OCULOS DE SEGURANÇA','Q3',0,0,6);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(19,'MACACAO DE SEGURANÇA','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(20,'CAPACETE','Q3',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(21,'CALÇA FARDA','Q3',0,0,6);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(22,'LUVA ADERENTE','Q3',0,0,8);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(23,'CAMISA FARDA','Q3',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(24,'RESPIRADOR DESCARTAVEL SEM VALVULA','Q3',0,0,19);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(25,'MASCARA COM FILTRO','Q3',0,0,02);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(26,'LUVA DE PANO','Q3',0,0,7);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(27,'LUBRIFICANTE','Q3',0,0,5);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(28,'PEÇA DE PVC','Q3',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(29,'PROTETOR ORICULAR','Q3',0,0,11);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(30,'DUREX LARGO','Q3',0,0,05);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(31,'FITA CREPE','Q3',0,0,10);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(32,'FITA DEMARCAÇAO VERMELHA','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(33,'FITA DEMARCAÇAO AZUL','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(34,'ADESIVO DE CONTATO','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(35,'ADESIVO PLASTICO PARA PVC','Q3',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(36,'FLUIDO DE CORTE A BASE DE AGUA','Q3',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(37,'BOTA','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(38,'LIXA A40','Q3',0,0,35);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(39,'LIXA A60','Q3',0,0,39);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(40,'LIXA A80','Q3',0,0,36);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(41,'LIXA A120','Q3',0,0,31);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(42,'LIXA A320','Q3',0,0,37);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(43,'LIXA A60','Q3',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(44,'LIXA A30','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(45,'LIXA CAR50 36','Q3',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(46,'LIXA A80','Q3',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(47,'LIXA A46','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(48,'APLICADOR PARA MASSA','Q3',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(49,'ESTILETE','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(50,'FIXA FIO','Q3',0,0,18);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(51,'FITA VEDA ROSCA','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(52,'FITA ISOLANTE','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(53,'ALICATE UNIVERSAL ','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(54,'CHAVE ESTRELA','Q3',0,0,5);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(55,'PA','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(56,'PARAFUSO','Q3',0,0,6);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(57,'BUCHA N8','Q3',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(58,'LIXA MAX RPM GR 60','Q3',0,0,6);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(59,'LIXA MAX RPM GR 80','Q3',0,0,7);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(60,'ROLO 230 MM','Q3',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(61,'ROLO 90 MM','Q3',0,0,7);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(62,'PINCEL 1.1/2 POL.','Q3',0,0,3);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(63,'PINCEL 2 POL.','Q3',0,0,5);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(64,'PAPEL OFICIO RESMA','Q4',0,0,11);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(65,'PASTA ARQUIVO','Q4',0,0,6);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(66,'ROLO PAPEL A1','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(67,'BALANÇA','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(68,'PLACA SALA DE APOIO','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(69,'PLACA SALA DE TREINAMENTO','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(70,'EXTINTOR PO QUIMICO','Q4',0,0,8);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(71,'PLACA AREA PARA FUMANTES ','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(72,'PLACA SEGURANÇA EP1','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(73,'PLACA BAIA TEMPORARIA DE RESIDUOS PERIGOSOS','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(74,'PLACA LABORATORIO SOLDAGEM','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(75,'PLACA EXTINTOR CO2','Q4',0,0,13);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(76,'PLACA INSPEÇAO','Q4',0,0,15);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(77,'PLACA IDENTIFICAÇAO E SERVIÇO','Q4',0,0,15);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(78,'ADESIVO RECICLAGEM','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(79,'ADESIVO RESIDUOS PERIGOSOS RECICLAGEM','Q4',0,0,1);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(80,'ADESIVO 110V PEQUENO','Q4',0,0,4);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(81,'ADESIVO EQUIPAMENTO ENERGIZADO','Q4',0,0,7);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(82,'ADESIVO 110V GRANDE','Q4',0,0,10);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(83,'PASTA SUSPENSA','Q4',0,0,2);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(84,'PASTA DE IDENTIFICAÇAO','Q4',0,0,125);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(85,'PLACA DE PATRIMONIO CAIXA COM 100','Q4',0,0,8);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(86,'PLACA DE SERVIO CAIXA COM 100','Q4',0,0,7);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda,quantidade) values(87,'PORTA CRACHA','Q4',0,0,879);