insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(1,'AGUA SANITARIA','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(2,'ODORIZANTE DE AMBIENTE','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(3,'INCETICIDA','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(4,'ALCOOL 92,8','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(5,'LIMPADOR PARA USO GERAL','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(6,'DETERGENTE','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(7,'ESPONJA DE LIMPEZA','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(8,'PEDRA SANITARIA','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(9,'PASTA MULTI-USO','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(10,'PANO MULTI-USO','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(11,'VASSOURA','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(12,'SACO LIXO 40L PCT. COM 100','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(13,'TOALHA DE PAPEL SANITARIO','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(14,'PAPEL HIGIENICO 4 ROLOS','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(15,'PANO DE CHAO','Q2',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(16,'TELEFONE','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(17,'LUVA PVC EMBORRACHADA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(18,'OCULOS DE SEGURANÇA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(19,'MACACAO DE SEGURANÇA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(20,'CAPACETE','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(21,'CALÇA FARDA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(22,'LUVA ADERENTE','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(23,'CAMISA FARDA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(24,'RESPIRADOR DESCARTAVEL SEM VALVULA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(25,'MASCARA COM FILTRO','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(26,'LUVA DE PANO','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(27,'LUBRIFICANTE','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(28,'PEÇA DE PVC','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(29,'PROTETOR ORICULAR','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(30,'DUREX LARGO','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(31,'FITA CREPE','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(32,'FITA DEMARCAÇAO VERMELHA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(33,'FITA DEMARCAÇAO AZUL','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(34,'ADESIVO DE CONTATO','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(35,'ADESIVO PLASTICO PARA PVC','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(36,'FLUIDO DE CORTE A BASE DE AGUA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(37,'BOTA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(38,'LIXA A40','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(39,'LIXA A60','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(40,'LIXA A80','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(41,'LIXA A120','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(42,'LIXA A320','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(43,'LIXA A60','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(44,'LIXA A30','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(45,'LIXA CAR50 36','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(46,'LIXA A80','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(47,'LIXA A46','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(48,'APLICADOR PARA MASSA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(49,'ESTILETE','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(50,'FIXA FIO','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(51,'FITA VEDA ROSCA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(52,'FITA ISOLANTE','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(53,'ALICATE UNIVERSAL ','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(54,'CHAVE ESTRELA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(55,'PA','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(56,'PARAFUSO','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(57,'BUCHA N8','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(58,'LIXA MAX RPM GR 60','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(59,'LIXA MAX RPM GR 80','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(60,'ROLO 230 MM','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(61,'ROLO 90 MM','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(62,'PINCEL 1.1/2 POL.','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(63,'PINCEL 2 POL.','Q3',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(64,'PAPEL OFICIO RESMA','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(65,'PASTA ARQUIVO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(66,'ROLO PAPEL A1','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(67,'BALANÇA','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(68,'PLACA SALA DE APOIO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(69,'PLACA SALA DE TREINAMENTO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(70,'EXTINTOR PO QUIMICO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(71,'PLACA AREA PARA FUMANTES ','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(72,'PLACA SEGURANÇA EP1','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(73,'PLACA BAIA TEMPORARIA DE RESIDUOS PERIGOSOS','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(74,'PLACA LABORATORIO SOLDAGEM','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(75,'PLACA EXTINTOR CO2','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(76,'PLACA INSPEÇAO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(77,'PLACA IDENTIFICAÇAO E SERVIÇO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(78,'ADESIVO RECICLAGEM','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(79,'ADESIVO RESIDUOS PERIGOSOS RECICLAGEM','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(80,'ADESIVO 110V PEQUENO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(81,'ADESIVO EQUIPAMENTO ENERGIZADO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(82,'ADESIVO 110V GRANDE','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(83,'PASTA SUSPENSA','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(84,'PASTA DE IDENTIFICAÇAO','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(85,'PLACA DE PATRIMONIO CAIXA COM 100','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(86,'PLACA DE SERVIO CAIXA COM 100','Q4',0,0);
insert into produto_mi(codigo,nome,local_estoque,valor_custo,valor_venda) values(87,'PORTA CRACHA','Q4',0,0);